package passwordgeneratorthing;
public class GeneratorGUI extends javax.swing.JDialog{
  Generator gen = null;
  
  public GeneratorGUI(java.awt.Frame parent, boolean modal){
    super(parent, modal);
    initComponents();
    this.gen = new Generator(10);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lengthLabel = new javax.swing.JLabel();
    passwordLabel = new javax.swing.JLabel();
    passwordField = new javax.swing.JTextField();
    lengthField = new javax.swing.JTextField();
    generateButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    lengthLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    lengthLabel.setText("Length");

    passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    passwordLabel.setText("Password");

    passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    passwordField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        passwordFieldActionPerformed(evt);
      }
    });

    lengthField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lengthField.setText("10");
    lengthField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        lengthFieldActionPerformed(evt);
      }
    });
    lengthField.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusLost(java.awt.event.FocusEvent evt) {
        lengthFieldFocusLost(evt);
      }
    });

    generateButton.setText("Generate");
    generateButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        generateButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(passwordLabel)
          .addComponent(lengthLabel))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(generateButton)
          .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lengthField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lengthLabel)
          .addComponent(lengthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(passwordLabel)
          .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(generateButton)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
    this.passwordField.setText(this.gen.generate());
  }//GEN-LAST:event_generateButtonActionPerformed

  private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
    this.generateButtonActionPerformed(evt);
  }//GEN-LAST:event_passwordFieldActionPerformed

  private void lengthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthFieldActionPerformed
    this.passwordField.grabFocus();
  }//GEN-LAST:event_lengthFieldActionPerformed

  private void lengthFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lengthFieldFocusLost
    this.gen.length = Integer.parseInt(this.lengthField.getText());
  }//GEN-LAST:event_lengthFieldFocusLost

  public static void main(String args[]){
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
        if("Nimbus".equals(info.getName())){
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch(ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch(InstantiationException ex) {
      java.util.logging.Logger.getLogger(GeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch(IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch(javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable(){
      public void run(){
        GeneratorGUI dialog = new GeneratorGUI(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter(){
          @Override
          public void windowClosing(java.awt.event.WindowEvent e){
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton generateButton;
  private javax.swing.JTextField lengthField;
  private javax.swing.JLabel lengthLabel;
  private javax.swing.JTextField passwordField;
  private javax.swing.JLabel passwordLabel;
  // End of variables declaration//GEN-END:variables
}
